"""empty message

Revision ID: 102bac14fff7
Revises: 
Create Date: 2021-04-15 23:45:10.127092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102bac14fff7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=124), nullable=True),
    sa.Column('address', sa.String(length=124), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('phonenumber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=128), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phonenumber')
    op.drop_table('person')
    # ### end Alembic commands ###
