"""empty message

Revision ID: ff21c3764aac
Revises: 102bac14fff7
Create Date: 2021-04-16 01:13:45.077167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff21c3764aac'
down_revision = '102bac14fff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'phonenumber', ['number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phonenumber', type_='unique')
    # ### end Alembic commands ###
